@baseUrl = http://localhost:3001
@jwtToken = {{authLogin.response.body.accessToken}}

@postUuid = {{createPostOwned.response.body.id}}
@postSlug = {{createPostOwned.response.body.slug}}
@imagePath = {{uploadImage.response.body.url}}
@imageUrl = {{baseUrl}}{{imagePath}}
@imageUuid = {{uploadImage.response.body.id}}

@userNameForTesting = Júlia
@userEmailForTesting = julia@email.com
@userPasswordForTesting = 123458
@userNewPasswordForTesting = 1234589

# AUTH ########################################################################

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{userEmailForTesting}}",
  "password": "{{userPasswordForTesting}}"
}

# USER ########################################################################

### Create user
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "{{userNameForTesting}}",
  "email": "{{userEmailForTesting}}",
  "passwordHash": "{{userPasswordForTesting}}"
}

### Update user
# @name updateUser
PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "{{userNameForTesting}}",
  "email": "{{userEmailForTesting}}"
}

### Update user password
# @name updateUserPassword
PATCH {{baseUrl}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "currentPasswordHash": "{{userPasswordForTesting}}",
  "newPasswordHash": "{{userNewPasswordForTesting}}"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}

### Delete one user
# @name deleteOneUser
DELETE {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}

# POST ########################################################################

### Create post owned
# @name createPostOwned
POST {{baseUrl}}/post/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "title": "Título do post",
  "excerpt": "Excerto Excerto Excerto Excerto",
  "content": "Conteúdo",
  "coverImage": "https://res.cloudinary.com/dqixnu2tr/image/upload/v1786474915/2026-08-11/1786474934393-72ka8x.webp"
}

### Read all post public
# @name readAllPostPublic
GET {{baseUrl}}/post/

### Read one post public
# @name readOnePostPublic
GET {{baseUrl}}/post/{{postSlug}}

### Read all post owned
# @name readAllPostOwned
GET {{baseUrl}}/post/me
Authorization: Bearer {{jwtToken}}

### Read one post owned
# @name readOnePostOwned
GET {{baseUrl}}/post/me/{{postUuid}}
Authorization: Bearer {{jwtToken}}

### Update one post owned
# @name updateOnePostOwned
PATCH {{baseUrl}}/post/me/{{postUuid}}
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "title": "NOVO - Título do post",
  "excerpt": "NOVO - Excerto",
  "content": "NOVO - Conteúdo",
  "published": true
}

### Delete one post owned
# @name deleteOnePostOwned
DELETE {{baseUrl}}/post/me/{{postUuid}}
Authorization: Bearer {{jwtToken}}

# UPLOAD ######################################################################

### Upload Image
# @name uploadImage
POST {{baseUrl}}/upload
Authorization: Bearer {{jwtToken}}
Content-Type: multipart/form-data; boundary=----BryenFormBoundary

------BryenFormBoundary
Content-Disposition: form-data; name="file"; filename="image.png"
Content-Type: image/png

< ../dev/images/image.jpeg
------BryenFormBoundary--




### FIND ALL IMAGES
# @name findAllImages
GET {{baseUrl}}/images
Authorization: Bearer {{jwtToken}}

### FIND ALL IMAGES OWNED
# @name findAllImagesOwned
GET {{baseUrl}}/images/me
Authorization: Bearer {{jwtToken}}
 
### DELETE IMAGE
# @name deleteImage
DELETE  {{baseUrl}}/images/ff280828-720d-493b-9b40-d3f8ebe28723
Authorization: Bearer {{jwtToken}}
 
### FIND ALL IMAGES OWNED
# @name findAllImages
GET {{baseUrl}}/images/me/
Authorization: Bearer {{jwtToken}}
 
###############################################################################